services:
  - type: web
    name: travel-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GROQ_API_KEY
        sync: false
      - key: DUFFEL_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: travel-data
      mountPath: /opt/travel/data
      sizeGB: 1
